services:
  worker-1:
    image: bitwiselearn/worker
    restart: always
    privileged: true
    env_file:
      - ./.env
  worker-2:
    image: bitwiselearn/worker
    restart: always
    privileged: true
    env_file:
      - ./.env
  worker-3:
    image: bitwiselearn/worker
    restart: always
    privileged: true
    env_file:
      - ./.env
