services:
  frontend-1:
    image: bitwiselearn/frontend
    restart: always
    privileged: true
    ports:
      - 3000:3000
    env_file:
      - ./.env
  frontend-2:
    image: bitwiselearn/frontend
    restart: always
    privileged: true
    ports:
      - 3001:3000
    env_file:
      - ./.env
  frontend-3:
    image: bitwiselearn/frontend
    restart: always
    privileged: true
    ports:
      - 3002:3000
    env_file:
      - ./.env
